import {
  addAppAction,
  appInstalledByUser,
  checkAndRevalidateUserPage,
  getAppById,
  getAppsForTesting,
  getNotUserAppList,
  getUserAppList,
  getUserAppTesters,
  revalidatePathUser,
  getUserAppTestersEmails,
  getAllTesterEmails,
  addUsersAsTesters,
  isNotAddedTesters,
  addAsTesters,
  markAppHasEnoughInstalls,
  markAppTestCompleted,
  rmAsTesters,
} from './appActions';

export const appAction = {
  addApp: addAppAction,
  appInstalledByUser,
  getAppsForTesting,
  getAppById,
  getUserAppList,
  revalidatePathUser,
  getNotUserAppList,
  getUserAppTesters,
  checkAndRevalidateUserPage,
  getUserAppTestersEmails,
  getAllTesterEmails,
  addUsersAsTesters,
  isNotAddedTesters,
  addAsTesters,
  markAppHasEnoughInstalls,
  markAppTestCompleted,
  rmAsTesters,
} as const;
